apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pools:
      - subnet: 192.168.0.0/16
        pool: 192.168.2.1-192.168.2.254
        aggregation: default