apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pools:
      - subnet: 10.8.8.0/24
        pool: 10.8.8.201-10.8.8.254
        aggregation: default