apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gotify-https
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: v1
kind: Service
metadata:
  name: gotify-https
  labels:
    app: gotify-https
    service: gotify
spec:
  ports:
    - port: 443
      name: https
  selector:
    app: gotify
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gotify-route-https
spec:
  parentRefs:
    - name: gotify-https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gotify-https
          port: 443
