apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: cloudflared
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ping_group_range
            value: "65532 65532"
      containers:
        - command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - run
          args:
            - --token
            - $(TOKEN)
          image: cloudflare/cloudflared:latest
          name: cloudflared
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: token
                  key: token