apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml



helmCharts:
  - name: couchdb
    namespace: couchdb
    releaseName: couchdb
    valuesFile: values.yaml
    includeCRDs: true


patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add 
        path: /metadata/labels
        value: 
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/enforce-version: latest
            pod-security.kubernetes.io/warn: privileged
