apiVersion: v1
kind: ConfigMap
metadata:
  name: master
  namespace: dont-starve
data:
  server.ini: |  
    [NETWORK]
    server_port = 11000
    
    [SHARD]
    is_master = true
    
    [STEAM]
    master_server_port = 27018
    authentication_port = 8768

  worldgenoverride.lua: |
    return {
        override_enabled = true,
        preset = "SURVIVAL_TOGETHER",
        overrides = {},
    }

  modoverrides.lua: |
    return {
      ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
      ["workshop-378160973"]={
        configuration_options={
          ENABLEPINGS=true,
          FIREOPTIONS=2,
          OVERRIDEMODE=false,
          SHAREMINIMAPPROGRESS=true,
          SHOWFIREICONS=true,
          SHOWPLAYERICONS=true,
          SHOWPLAYERSOPTIONS=2 
        },
        enabled=true 
      },
      ["workshop-666155465"]={
        configuration_options={
          chestB=-1,
          chestG=-1,
          chestR=-1,
          display_hp=-1,
          food_estimation=-1,
          food_order=0,
          food_style=0,
          lang="auto",
          show_food_units=-1,
          show_uses=-1 
        },
        enabled=true 
      } 
    }    

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caves
  namespace: dont-starve
data:
  server.ini: |
    [NETWORK]
    server_port = 11001
    
    [SHARD]
    is_master = false
    name = Caves
    
    [STEAM]
    master_server_port = 27019
    authentication_port = 8769

  worldgenoverride.lua: |
    return {
      override_enabled = true,
      preset = "DST_CAVE",
      overrides = {},
    }

  modoverrides.lua: |
    return {
      ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
      ["workshop-378160973"]={
        configuration_options={
          ENABLEPINGS=true,
          FIREOPTIONS=2,
          OVERRIDEMODE=false,
          SHAREMINIMAPPROGRESS=true,
          SHOWFIREICONS=true,
          SHOWPLAYERICONS=true,
          SHOWPLAYERSOPTIONS=2 
        },
        enabled=true 
      },
      ["workshop-666155465"]={
        configuration_options={
          chestB=-1,
          chestG=-1,
          chestR=-1,
          display_hp=-1,
          food_estimation=-1,
          food_order=0,
          food_style=0,
          lang="auto",
          show_food_units=-1,
          show_uses=-1 
        },
        enabled=true 
      } 
    }